#!name=555燃費
#!desc=555燃費去廣告
#!author=@ddgksf2013
#!UpdateTime=2023-08-13
#去除首頁輪播廣告、首頁信息流廣告、我的頁面推廣

[URL Rewrite]

^https?:\/\/[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+){1,3}(:\d+)?\/api\/v\d\/advert - reject

[Script]

555Ad = type=http-response,pattern=^https?:\/\/[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+){1,3}(:\d+)?\/api\/v\d\/movie\/index_recommend,requires-body=1,max-size=0,script-path=https://github.com/ddgksf2013/Scripts/raw/master/555Ad.js

[MITM]

hostname = %APPEND% run.api.qyfxgd.cn,*.weilai555.com,*.ecoliving168.com