#!name=555
#!desc=555去廣告
#!author=@ddgksf2013
#!UpdateTime=2023-11-30
#去除首頁輪播廣告、首頁信息流廣告、我的頁面推廣

[URL Rewrite]

^https?:\/\/[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+){1,3}(:\d+)?\/api\/v\d\/advert - reject

[Script]

555Ad_11 = type=http-response, pattern=^https?:\/\/[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+){1,3}(:\d+)?\/api\/v\d\/movie\/index_recommend, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/555Ad.js, timeout=60, script-update-interval=0

[MITM]

hostname = %APPEND% *.qyfxgd.cn,*.weilai555.com,*.ecoliving168.com