#!name=菜鸟去广告
#!desc=菜鸟去广告
#!author=@ddgksf2013
#!UpdateTime=2023-06-15

[URL Rewrite]

# > 菜鸟裹裹_通用广告请求@ddgksf2013
^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.guoguo\.nbnetflow\.ads\.(show|mshow)\.cn\/ - reject-200
# > 菜鸟裹裹_支付宝小程序_通用广告请求@ddgksf2013
^https?:\/\/guide-acs\.m\.taobao\.com\/gw\/mtop\.cainiao\.guoguo\.nbnetflow\.ads\.show - reject-200
# > 菜鸟裹裹_支付宝小程序_底部商品推广@ddgksf2013
^https?:\/\/guide-acs\.m\.taobao\.com\/gw\/mtop\.cainiao\.adx\.flyad\.getad - reject-200
# > 菜鸟裹裹_支付宝小程序_匿名选择@ddgksf2013
^https?:\/\/guide-acs\.m\.taobao\.com\/gw\/mtop\.cainiao\.nbmensa\.research\.researchservice\.consultmerge - reject-200

[Script]

# > 菜鸟裹裹_amdc处理[Anti已将Amdc分流删除,故更换屏蔽策略]@ddgksf2013
amdc = type=http-response,pattern=^http:\/\/amdc\.m\.taobao\.com,requires-body=1,max-size=0,script-path=https://github.com/ddgksf2013/Scripts/raw/master/amdc.js
# > 菜鸟裹裹_首页中部的惊喜福利推广@ddgksf2013
cainiao_json = type=http-response,pattern=^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.nbpresentation\.protocol\.homepage\.get\.cn,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/cainiao_json.js
# > 菜鸟裹裹_搜索框下方今日好物推荐@ddgksf2013
cainiao_json = type=http-response,pattern=^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.adkeyword,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/cainiao_json.js
# > 菜鸟裹裹_首页底部商品推广@ddgksf2013
cainiao_json = type=http-response,pattern=^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.guoguo\.nbnetflow\.ads\.index\.cn,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/cainiao_json.js
# > 菜鸟裹裹_支付宝小程序_中部的寄件推广[导致的空白占位后续处理]@ddgksf2013
cainiao_json = type=http-response,pattern=^https?:\/\/guide-acs\.m\.taobao\.com\/gw\/mtop\.cainiao\.guoguo\.nbnetflow\.ads\.mshow,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/cainiao_json.js

[MITM]

hostname = %APPEND% cn-acs.m.cainiao.com,guide-acs.m.taobao.com