#!name=Emby
#!desc=Emby 解鎖播放權限
#!author=@KleinerSource
#!UpdateTime=2024-01-17

[Script]
Emby = type=http-request, pattern=^https:\/\/mb3admin\.com\/admin\/service(\/registration\/validateDevice|\/appstore\/register|\/registration\/validate|\/registration\/getStatus|\/supporter\/retrievekey), script-path=https://raw.githubusercontent.com/chxm1023/script/main/Rewrite/embycrack.js, timeout=60

[MITM]
hostname = %APPEND% mb3admin.com