#!name=JD_Price
#!desc=京東比價，僅支持京東的標準模式，點擊商品標題即可查看。
#!author=@wf021325
#!UpdateTime=2024-12-23

[Script]

JD_Price = type=http-response, pattern=^https?:\/\/api\.m\.jd\.com/client\.action\?functionId=(wareBusiness|serverConfig|basicConfig), script-path=https://raw.githubusercontent.com/wf021325/qx/master/js/jd_price.js, requires-body=true, max-size=-1, timeout=60

[MITM]

hostname = %APPEND% api.m.jd.com