#!name=VVebo
#!desc=VVebo修復用戶主頁
#!author=@ddgksf2013
#!UpdateTime=2023-11-30

[URL Rewrite]
^https:\/\/api\.weibo\.cn\/2\/profile\/statuses\/tab\? https://raw.githubusercontent.com/suiyuran/stash/main/scripts/fix-vvebo-user-timeline.js PROXY
^https:\/\/api\.weibo\.cn\/2\/statuses\/user_timeline\? https://raw.githubusercontent.com/suiyuran/stash/main/scripts/fix-vvebo-user-timeline.js PROXY
^https:\/\/api\.weibo\.cn\/2\/users\/show\? https://raw.githubusercontent.com/suiyuran/stash/main/scripts/fix-vvebo-user-timeline.js PROXY
[Script]
Vvebo-request = type=http-request,pattern=^https:\/\/api\.weibo\.cn\/2\/(users\/show\?|statuses\/user_timeline\?),requires-body=1,script-path=https://raw.githubusercontent.com/Keywos/rule/main/JS/vv.js

Vvebo_response = type=http-response,pattern=^https:\/\/api\.weibo\.cn\/2\/profile\/statuses\/tab\?,requires-body=1,script-path=https://raw.githubusercontent.com/Keywos/rule/main/JS/vv.js

[MITM]
hostname = %INSERT% api.weibo.cn
